### ISSUE TITLE
ERROR pip install -r requirements.txt 小白搞不懂

### ISSUE THREAD

**Issue by changjiuxiong** [OedoSoldier/chatglm_webui#2]
ERROR: Cannot install -r requirements.txt (line 3) because these package versions have conflicting dependencies.

The conflict is caused by:
    icetk 0.0.5 depends on torchvision
    icetk 0.0.4 depends on torchvision
    icetk 0.0.3 depends on torchvision
    icetk 0.0.2 depends on torchvision
    icetk 0.0.1 depends on torchvision

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by OedoSoldier** [comment]
你没装pytorch，先跑个`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117`

**Comment by wumulong-469** [comment]
估计是你的python版本太高了。在kali（现在是2023.1的快照源）使用的是python3.11下，安装也和你有相同报错问题。在手动pip install torchvision 会告诉你没有合适的版本。最后我是用conda 创建 3.10的环境解决的，希望可以帮到你。
