### ISSUE TITLE
14875 killed     python main.py --low_vram

### ISSUE THREAD

**Issue by neeeeeeeeeeee** [OedoSoldier/chatglm_webui#3]
❯ python main.py --low_vram
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  88%|███████████████▊  | 7/8 [00:12<00:01,  1.84s/it][1]    14875 killed     python main.py --low_vram

大佬这是为什么呢，16g内存爆内存了吗

**Comment by OedoSoldier** [comment]
你看下任务管理器，有可能是爆内存了。加载的时候内存消耗很大，把别的程序先关了，加载起来之后再打开

**Comment by ymhierarch** [comment]
大佬,不能直接把模型加载到显存吗

**Comment by neeeeeeeeeeee** [comment]
那应该是g了，我是Fedora，关了所有程序之后也爆了，换台电脑试试吧，谢谢大佬了
